project_jaffle_shop:
  outputs:
    dev:
      dataset: "{{ env_var('PROJECT_DATASET') }}"
      job_execution_timeout_seconds: "{{ env_var('DBT_JOB_TIMEOUT') | int }}"
      job_retries: "{{ env_var('DBT_JOB_RETRIES') | int }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: "{{ env_var('DBT_LOCATION') }}"
      method: "{{ env_var('DBT_METHOD') }}"
      priority: "{{ env_var('DBT_PRIORITY') }}"
      project: "{{ env_var('PROJECT_ID') }}"
      threads: "{{ env_var('DBT_THREADS') | int }}"
      type: bigquery
  target: dev
